db.user=${MYSQL_USER:user}
db.password=${MYSQL_PASSWORD:password}
db.host=${MYSQL_HOST:localhost}
db.port=${MYSQL_PORT:3306}
db.name=${MYSQL_DATABASE:gestao_tickets}
db.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:gestao_tickets}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
